# Generated by Django 5.0.1 on 2024-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reviews', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Pickup', 'Pickup')], max_length=100)),
                ('company', models.CharField(default='Unknown', max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
        ),
    ]
