# Generated by Django 5.0.5 on 2024-05-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Car',
            fields=[
                ('product_car_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.product_car')),
                ('category', models.CharField(max_length=100)),
            ],
            bases=('home.product_car',),
        ),
    ]
