# Generated by Django 5.0.5 on 2024-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='daily_rental_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
    ]
