# Generated by Django 5.0.1 on 2024-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('driver_license', models.CharField(max_length=300)),
                ('cnic', models.CharField(max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('car_name', models.CharField(max_length=200)),
                ('car_company', models.CharField(max_length=200)),
                ('car_image', models.URLField()),
            ],
        ),
    ]
