# Generated by Django 5.0.1 on 2024-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car_image',
            field=models.CharField(max_length=500),
        ),
    ]
