# Generated by Django 5.0.1 on 2024-05-25 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_booking_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
