# Generated by Django 5.0.1 on 2024-05-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=15)),
                ('car_name', models.CharField(max_length=100)),
                ('car_company', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Pickup', 'Pickup')], max_length=20)),
                ('car_description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('engine', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=10)),
            ],
        ),
    ]
